---
title: "Informazioni"
subtitle: "Il progetto sui \"Dati aperti sul PNRR\""
format:
  html:
    toc: true
---

La presente guida è a cura dall'[**associazione onData**](https://www.ondata.it/), in collaborazione con **altre organizzazioni** e **altre persone**, che si sono incontrate e confrontate sul tema dei dati aperti e della trasparenza nel Piano Nazionale Ripresa e Resilienza (PNRR), e che hanno collaborato sul tema in diversi contesti.

È una **guida** al **monitoraggio civico** del PNRR **attraverso i dati attualmente disponibili**. Si propone di affiancare le cittadine e i cittadini nel monitoraggio civico di un piano che avrà un impatto decisivo sul futuro del nostro Paese.<br>
I dati aperti sono ancora pochi e ci piace pensare che presto saranno interamente pubblicati.

Nell'attesa, **apriamo questo spazio come un bene comune** per tutte/i coloro che vorranno usarlo e/o [contribuire ad arricchirlo](partecipa.qmd).

Questo _vademecum_ non sarebbe nato senza il "**fare cose, vedere gente**" in questi contesti:

- il progetto [**datiBeneComune**](https://www.datibenecomune.it/) - che chiede a Governo e Parlamento **dati aperti e _machine-readable_** sui principali **temi di interesse dei cittadini e delle cittadine**, a partire dai dati sul **PNRR**;
- le riunioni dei tavoli dell'[Azione 5.02](https://open.gov.it/governo-aperto/piano-nazionale/5nap/azione-5/impegno-502) - Standard aperti per l’inclusività e la partecipazione della società civile nel monitoraggio della spesa pubblica - del "**5° Piano d’Azione Nazionale per il governo aperto**", a cui hanno partecipato e partecipano alcuni dei soggetti che hanno contribuito a questo progetto;
- l'[**Osservatorio Civico PNRR**](https://osservatoriocivicopnrr.it/) e le sue scuole di monitoraggio. Vivendole e alimentandole, è emerso quanto potesse essere utile un _vademecum_ per i cittadini e le cittadine, per aiutarli a capire meglio il PNRR e a monitorarlo e sono venute fuori diverse idee poi sviluppate qui;
- una [**rete** della **società civile** per il monitoraggio del PNRR](rete-pnrr.md), che condividono regolarmente stato dell'arte e criticità delle loro iniziative e progettualità sul tema e concordano iniziative congiunte.


## Licenza

La licenza scelta è la [`CC-BY-4.0`](https://creativecommons.org/licenses/by/4.0/deed.it) (Creative Commons Attribution 4.0 International). Quindi sei libero di usare come preferisci i contenuti di questo spazio, avendo cura di [citare la fonte](#come-citare-la-fonte).

### Come citare la fonte

A titolo d'esempio, è sufficiente indicare "[Vademecum PNRR a cura dell'associazione onData](https://pnrr.datibenecomune.it/)" (inserendo anche il link alla home, `https://pnrr.datibenecomune.it`).

---

Questo sito è costruito con ❤️, ⚒️, un po' di 🤯 e con [Quarto](https://quarto.org/).
