---
title: "Introduzione"
subtitle: "Monitorare i progetti del PNRR e PNC"
---

Il **Piano nazionale di Ripresa e Resilienza** (**PNRR**) italiano prevede investimenti pari a **191,5 miliardi di euro**, finanziati dall'Unione Europea attraverso il Dispositivo per la Ripresa e la Resilienza (RRF), a cui **si aggiungono 30,6 miliardi di risorse nazionali**, del **Piano Nazionale per gli investimenti Complementari** (**PNC**) confluite in un apposito Fondo nazionale complementare al PNRR, per un **totale di 222,1 miliardi di euro** (a cui si aggiungono ulteriori 13 miliardi del programma React EU).

Per comprenderlo, seguirne lo sviluppo, monitoralo e valutarne l'impatto è **necessario** poter **accedere ai dati correlati** (vedi [**I dati che Vorrei**](https://vorrei.datibenecomune.it/dati-che-vorrei/dati/)).

Prima di passare all'elenco di alcune banche dati di interesse e a come usarle, si vogliono sottolineare **alcuni punti importanti**:

- l'**accesso ai dati** e la loro analisi, è soltanto **uno degli step** di un percorso di studio e [**monitoraggio**](monitoraggio/index.qmd);
- **fare sempre riferimento ai documenti ufficiali** in cui si assegnano dei fondi (come ad esempio i documenti della pagina di concessione del [PINQuA](https://trasparenza.mit.gov.it/index.php?id_oggetto=38&id_doc=104527)) e **partire da questi** per ulteriori approfondimenti basati su banche dati. Non sono purtroppo sempre facilmente accessibili/reperibili;
- **contattare la Pubblica Amministrazione (PA) destinataria del fondo**, per chiedere **ulteriori informazioni**, **documentazione** e **dati**, a integrazione delle banche dati aperte (come quelle descritte sotto). Queste infatti spesso rappresentano **soltanto una parte delle informazioni necessarie** per comprendere e valutare un progetto di finanziamento pubblico.


## Fonti dati nazionali

A seguire un elenco delle fonti dati nazionali sulla realizzazione dei singoli progetti d'investimento **PNRR** e **PNC** in Italia, ognuno definito da un Codice Unico di Progetto (CUP) che identifica un progetto d'investimento pubblico.<br>

Elenco:

1. [ReGIS](https://www.italiadomani.gov.it/it/Interventi/regis---il-sistema-gestionale-unico-del-pnrr.html), è lo strumento unico attraverso cui le Amministrazioni centrali e territoriali interessate devono adempiere agli obblighi di monitoraggio, rendicontazione e controllo delle misure e dei progetti finanziati dal PNRR. Il portale pubblica per adesso alcune estrazioni di dati in formato aperto, sul monitoraggio della programmazione di spesa e investimenti delle misure sul [portale Italia Domani](https://www.italiadomani.gov.it/content/sogei-ng/it/it/catalogo-open-data.html), ancora **poco relativamente a livello di progetti e stato di avanzamento**. Il sistema è gestito da Ministero dell’Economia e delle Finanze – Dipartimento della Ragioneria Generale dello Stato – Servizio Centrale per il PNRR;
2. [**OpenCUP**](fonti/opencup/index.qmd), il portale con i dati, in formato aperto, sulle decisioni di investimento pubblico finanziate con fondi pubblici nazionali, comunitarie o regionali o con risorse private registrate con il Codice Unico di Progetto ed è gestito dalla Presidenza del Consiglio dei Ministri - Dipartimento per la programmazione e il coordinamento della politica economica (DIPE);
3. il [Catalogo dei dati aperti](fonti/anac/index.qmd) di alcune informazioni estratte dalla Banca dati nazionale dei contratti pubblici (BDNCP) relativi alle gare ed appalti, con relativo codice identificativo della gara gestito dall'**Autorità Nazionale Anticorruzione** (ANAC);
4. la [**Banca dati Servizio Contratti Pubblici**](fonti/scp/index.qmd)  del Servizio contratti pubblici (SCP) del Ministero delle infrastrutture e dei trasporti (MIT);
5. [**OpenBDAP**](fonti/openbdap/index.qmd), portale OpenBDAP sezione "Opere pubbliche" dove sono pubblicati i dati di monitoraggio delle opere inviati alla BDAP dagli enti (pubblici o privati) che realizzano opere pubbliche ed è gestito dalla Ragioneria Generale dello Stato (RGS/MEF).

::: {.callout-tip}
## Suggerimento
L'**ordine** dell'elenco non è casuale: ti consigliamo di seguirlo e iniziare da [OpenCUP](fonti/opencup/index.qmd).
:::

---

In questo spazio facciamo riferimento spesso a termini come [`dataset`](glossario.md#dataset), [`dati aperti`](glossario.md#dati-aperti), ecc., che potrebbero non esserti noti.<br>Per questo stiamo preparando una [pagina di riferimento](glossario.md) (ancora in costruzione).

