---
title: "OpenCUP: Focus PNRR"
---

L'ultima versione dei dati OpenCUP con focus sul PNRR è quella di [gennaio 2023](https://opencup.gov.it/portale/documents/21195/117121/progetti_cup_20230120.xlsx).

Molto importante la nota relativa che si legge sul sito:

> Si sottolinea che i dati oggetto del rilascio open data, rappresentano gli **interventi candidati** nell'ambito del PNRR, **così come segnalati dai soggetti titolari dei singoli interventi in fase di generazione CUP**, ma che **potrebbero non essere ammessi ai finanziamenti del Piano** e successivamente finanziati da altre misure di spesa. **Per la lista definitiva dei progetti PNRR**, **si rimanda agli elenchi ufficiali emanati dalle Amministrazioni responsabili dei finanziamenti**.

::: {.callout-caution}
## Fai attenzione
Per la ragione sopra indicata, non è detto che un progetto in questo elenco sia stato con certezza finanziato dal PNRR. È però un punto di partenza per fare approfondimenti sul sito della Pubblica Amministrazione correlata al progetto.
:::


```{python}
#| echo: false
#| warning: false

from IPython.display import display, Markdown
import humanize
import locale
locale.setlocale(locale.LC_ALL,"it_IT.UTF-8")

humanize.i18n.activate("it_IT")

!if [ ! -f ../../data/opencup/opencup-focus-pnrr.csv ]; then \
  qsv excel --dates-whitelist 'Data' ../../data/opencup/progetti_cup_20230120.xlsx >../../data/opencup/opencup-focus-pnrr.csv;\
fi

!if [ ! -f tmp_summary.csv ]; then\
  <../../data/opencup/opencup-focus-pnrr.csv mlrgo --csv summary >tmp_summary.csv;\
fi

!if [ ! -f tmp_summary_italia.csv ]; then\
  <../../data/opencup/opencup-focus-pnrr.csv mlrgo --csv filter '$CODICE_STATO==5' then summary >tmp_summary_italia.csv;\
fi

!mlr --csv cut -f SOTTOSETTORE_INTERVENTO,CODICE_CUP,IMPO_IMPORTO_FINANZIATO then uniq -a then stats1 -a sum -f "IMPO_IMPORTO_FINANZIATO" -g SOTTOSETTORE_INTERVENTO then sort -nr IMPO_IMPORTO_FINANZIATO_sum then label SOTTOSETTORE_INTERVENTO,IMPORTO_FINANZIATO ../../data/opencup/opencup-focus-pnrr.csv >../../data/opencup/SOTTOSETTORE_INTERVENTO.csv

colonne=!<tmp_summary.csv mlr --c2n cut -f field_name | wc -l
righe=!<tmp_summary.csv mlr --c2n cut -f count then head -n 1

numero_cup=!<tmp_summary.csv mlr --c2n filter '$field_name=="CODICE_CUP"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
numero_stati=!<tmp_summary.csv mlr --c2n filter '$field_name=="CODICE_STATO"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
numero_regioni=!<tmp_summary_italia.csv mlr --c2n filter '$field_name=="CODI_CODICE_REGIONE"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
numero_province=!<tmp_summary_italia.csv mlr --c2n filter '$field_name=="CODI_CODICE_PROVINCIA"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
numero_comuni=!<tmp_summary_italia.csv mlr --c2n filter '$field_name=="CODI_CODICE_COMUNE"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
numero_settori=!<tmp_summary.csv mlr --c2n filter '$field_name=="SETTORE_INTERVENTO"' then put 'if($null_count>0){$distinct_count=$distinct_count-1}else{$distinct_count=$distinct_count}' then cut -f distinct_count
importo_finanziato=!<../../data/opencup/opencup-focus-pnrr.csv mlr --c2n cut -f CODICE_CUP,IMPO_IMPORTO_FINANZIATO then uniq -a then stats1 -a sum -f "IMPO_IMPORTO_FINANZIATO"

!if [ ! -f tmp_costi.csv ]; then\
  <../../data/opencup/opencup-focus-pnrr.csv mlrgo --csv cut -f CODICE_CUP,IMPO_COSTO_PROGETTO,IMPO_IMPORTO_FINANZIATO \
    then uniq -a then stats1 -a min,max,mode,p75,mean,sum -f IMPO_COSTO_PROGETTO,IMPO_IMPORTO_FINANZIATO  >tmp_costi.csv;\
fi

text=f"""

Il file si chiama [`progetti_cup_20230120.xlsx`](https://opencup.gov.it/portale/documents/21195/117121/progetti_cup_20230120.xlsx), ed è composto da **{int(righe[0]):n} righe** e **{int(colonne[0])} colonne**.


Inoltre:

- il numero di codici CUP è pari a **{int(numero_cup[0]):n}**;
- sono progetti riferibili a **{int(numero_stati[0])} stati**, e per l'**Italia** (più del 99% dei progetti) a **{int(numero_regioni[0])} regioni**, **{int(numero_province[0])} province** e **{int(numero_comuni[0]):n} comuni**.
- fanno riferimento a **{int(numero_settori[0])} settori** di intervento;
- l'importo finanziato totale è pari a **{humanize.intword(int(importo_finanziato[0]))} di €**.

::: aside
Il numero di Province e Comuni è maggiore del loro numero totale in Italia, perché probabilmente si fa riferimento a Comuni e Province che sono stati soppressi.
:::

"""

display(Markdown(text))
```

Alcune note utili sul file:

- contiene dei caratteri non correttamente codificati, e quindi non leggibili come ad esempio `dell¿abitare`;
- la preziosa colonna `DATA_GENERAZIONE_COMPLETO`, contiene le date in formato `mese/giorno/anno` (ad esempio `11/27/2020`). Sarebbe preferibile utilizzare lo standard `anno-mese-giorno` (`2020-11-27`);
- le suddivisioni territoriali, fanno probabilmente riferimento  al momento in cui è stato generato il codice CUP, ed è forse per questa ragione che c'è ad esempio un numero totale di Comuni diverso dal totale attuale.

::: {.callout-tip}
## Formato di pubblicazione alternativo

Proporremo a OpenCUP di pubblicare questo dataset anche in formato `parquet`[^parquet]. È un formato aperto, che rende l'accesso ai dati e la loro elaborazione molto rapida e efficiente. [Qui](../../data/opencup/opencup_focus_pnrr.parquet) lo stesso file in formato `parquet`.
:::

[^parquet]: il formato `parquet` <https://parquet.apache.org/>
