name: aggiorna pagina web dati Italiadomani

on:
  repository_dispatch:
  schedule:
    - cron:  '53 2 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Crea cartella utente bin, copia dentro l'eseguibile scrape, installa pandoc
      run: |-
        mkdir -p ~/bin
        cp bin/scrape ~/bin
        cp bin/mlr ~/bin
        cp bin/mlrgo ~/bin
        cd ~/bin
        chmod +x scrape
        chmod +x mlr
        chmod +x mlrgo
        sudo pip install yq
        sudo apt-get install -y pandoc

    - name: Installa Google Chrome (per scraping headless)
      run: |-
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Aggiorna pagina
      run: |-
        export PATH=$PATH:~/bin
        cd ./script/italia-domani/
        chmod +x ./italia-domani-pagina-catalogo.sh
        ./italia-domani-pagina-catalogo.sh

    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "pagina dati italiadomani: ${timestamp}" || exit 0
        git push
